# Generated by Django 4.2.7 on 2023-11-05 12:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_fields_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
